movie_project/movie_app/urls.py
from django.contrib import admin
from django.urls import path
from .views import index, AdminView, CreatePerson, EditPerson, ListPerson, CreateMovie, ListMovie, EditMovie, \
    CreateMovieRate, Movies, Login, Logout, SerializerView, SerializerDetail, MovieUpdateView, MovieListView, \
    ViewSets, MoviesDownloader, SuggestedMovies
from django.conf import settings
from django.conf.urls.static import static

app_name = 'movie_app'

urlpatterns = [
    path('', index, name='index'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('administration/', AdminView.main, name='administration'),
    path('administration/add/person/', CreatePerson.as_view(), name='create_person'),
    path('administration/people/', ListPerson.as_view(), name='list_people'),
    path('administration/edit/person/<pk>', EditPerson.as_view(), name='edit_person'),
    path('administration/add/movie/', CreateMovie.as_view(), name='create_movie'),
    path('administration/movies/', ListMovie.as_view(), name='list_movies'),
    path('administration/edit/movie/<pk>', EditMovie.as_view(), name='edit_movie'),
    path('administration/add/rate/', CreateMovieRate.as_view(), name='create_movie_rate'),
    # path('movies/', Movies.as_view(), name='movies'),
    path('serializer/', SerializerView.as_view(), name='serializer'),
    path('detail/<pk>', SerializerDetail.as_view(), name='detail'),
    path('movie/', MovieListView.as_view(), name='movie_list_create'),
    path('movie/<pk>', MovieUpdateView.as_view(), name='movie_detail_update_delete'),
    path('movies/<int:pk>/', ViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy', 'patch': 'partial_update'}), name='first'),
    path('movies/', ViewSets.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update'}), name='second'),
    path('movies/download', MoviesDownloader.as_view(), name='download'),
    path('movies/suggest', SuggestedMovies.as_view(), name='suggested_movies'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie_project/movie_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie_app.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        path(f'api/{settings.API_VERSION}/', include(('movie_app.api.urls', 'movie_app.api'), namespace='api-movie_app')),

    ] + urlpatterns

movie_project/movie_app/models.py
from django.db import models
from django.contrib.auth import get_user_model
from .choices import GENRES, RATING, ROLES, DEFAULT_GENRE


User = get_user_model()


class MoviePerson(models.Model):
    name = models.CharField(max_length=30)
    age = models.IntegerField()
    role = models.CharField(max_length=25, choices=ROLES)

    def __str__(self):
        return '{} is an {}'.format(self.name, self.role)


class Movie(models.Model):
    title = models.CharField(max_length=50)
    duration = models.IntegerField()
    detail = models.TextField(max_length=150)
    poster = models.ImageField(upload_to='movie_app/posters', max_length=100, default=None)
    movie_people = models.ManyToManyField(MoviePerson)
    trailer_url = models.URLField()
    genre = models.CharField(max_length=50, choices=GENRES, default=DEFAULT_GENRE)
    rating = models.FloatField(null=True, blank=True)
    original_language = models.CharField(max_length=50)
    release_date = models.DateField()
    country = models.CharField(max_length=50)

    def __str__(self):
        return self.title

    def image_url(self):
        if self.poster and hasattr(self.poster, 'url'):
            return self.poster.url


class MovieRate(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=150)
    rating = models.IntegerField(choices=RATING)

    def __str__(self):
        return '{} has {} of rate from {}'.format(self.movie, self.rating, self.user)


class UserToken(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=100)


class MovieSearch(models.Model):
    title = models.CharField(max_length=50)
    duration = models.IntegerField(null=True)
    detail = models.TextField(max_length=150)
    genre = models.CharField(max_length=50)
    original_language = models.CharField(max_length=50)
    release_date = models.DateField()
    country = models.CharField(max_length=50)
    poster = models.ImageField(upload_to='movie_app/posters', null=True, max_length=100, default=None, blank=True)
    actor = models.ManyToManyField('Actor')
    director = models.ForeignKey('Director', on_delete=models.CASCADE, null=True)


class Actor(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Director(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Suggest(models.Model):
    movie_title = models.CharField(max_length=100)

movie_project/templates/movie_app/admin/create/person.html
{% extends 'adminlte/base.html' %}

{% block content %}
    <div class="col-md-6">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Add Person</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" method="POST">
                 {% csrf_token %}
                  <div class="box-body">
                      <div class="form-group">
                        <label for="InputName">Name</label>

                        <input type="text" class="form-control" id="name" name="name" placeholder="Enter name" required>
                      </div>

                      <div class="form-group">
                        <label for="InputAge">Age</label>
                        <input type="number" class="form-control" id="age" name="age" placeholder="Enter age" required>
                        </div>
                      <div class="form-group">
                        <label>Role</label>
                            <select class="form-control" id="role" name="role">
                                {% if form %}
                                    {% for x, y in form.fields.role.choices %}
                                        <option value="{{ x }}"{% if form.fields.role.choices == x %} selected{% endif %}>{{ y }}</option>
                                    {% endfor %}
                                {% else %}
                                        <option>no role registered yet</option>
                                {% endif %}
                            </select>
                    </div>

                      <div class="box-footer">
                          <button type="submit" class="btn btn-primary" id="save">Save</button>
                      </div>
                  </div>
            </form>
          </div>
    </div>

{% endblock %}

movie_project/templates/movie_app/admin/create/rate.html
{% extends 'adminlte/base.html' %}

{% block content %}
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Add Rate</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="box-body">
                    <div class="form-group">
                        {{ form.movie.errors }}
                        <label for="id_movie">{{ form.movie.label }}</label><br>
                        <select class="form-control" id="id_movie" name="movie">
                            {% if form %}
                                {% for x, y in form.fields.movie.choices %}
                                    <option value="{{ x }}"{% if form.fields.movie.choices == x %}
                                            selected{% endif %}>{{ y }}</option>
                                {% endfor %}
                            {% else %}
                                <option>no movie registered yet</option>
                            {% endif %}
                        </select>
                    </div>

                    <div class="form-group">
                        {{ form.user.errors }}
                        <label for="id_user">{{ form.user.label }}</label><br>
                        <select class="form-control" id="id_user" name="user">
                            {% if form %}
                                {% for x, y in form.fields.user.choices %}
                                    <option value="{{ x }}"{% if form.fields.user.choices == x %}
                                            selected{% endif %}>{{ y }}</option>
                                {% endfor %}
                            {% else %}
                                <option>no user registered yet</option>
                            {% endif %}
                        </select>
                    </div>
                    <div class="form-group">
                        {{ form.comment.errors }}
                        <label for="comment">{{ form.comment.label }}</label>
                        <textarea class="form-control" rows="3" name="comment" id="comment"
                                  placeholder="Enter comment" required></textarea>
                    </div>
                    <div class="form-group">
                        {{ form.rating.errors }}
                        <label for="id_rate">{{ form.rating.label }}</label><br>
                        <select class="form-control" id="id_rate" name="rating">
                            {% if form %}
                                {% for x, y in form.fields.rating.choices %}
                                    <option value="{{ x }}"{% if form.fields.rating.choices == x %}
                                            selected{% endif %}>{{ y }}</option>
                                {% endfor %}
                            {% else %}
                                <option>no rate registered yet</option>
                            {% endif %}
                        </select>
                    </div>

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary" id="save">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

movie_project/templates/movie_app/admin/create/suggested_movies.html
{% extends 'adminlte/base.html' %}

{% block content %}
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Suggested Movies</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" method="POST">
               {% csrf_token %}
                <div class="box-body">
                    <div class="form-group">
                        {{ form.as_p }}
                    </div>
                </div>
                <!-- /.box-body -->

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}