movie_project/movie_app/urls.py
from django.contrib import admin
from django.urls import path
from .views import index, AdminView, CreatePerson, EditPerson, ListPerson, CreateMovie, ListMovie, EditMovie, \
    CreateMovieRate, Movies, Login, Logout, SerializerView, SerializerDetail, MovieUpdateView, MovieListView, \
    ViewSets, MoviesDownloader, SuggestedMovies
from django.conf import settings
from django.conf.urls.static import static

app_name = 'movie_app'

urlpatterns = [
    path('', index, name='index'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('administration/', AdminView.main, name='administration'),
    path('administration/add/person/', CreatePerson.as_view(), name='create_person'),
    path('administration/people/', ListPerson.as_view(), name='list_people'),
    path('administration/edit/person/<pk>', EditPerson.as_view(), name='edit_person'),
    path('administration/add/movie/', CreateMovie.as_view(), name='create_movie'),
    path('administration/movies/', ListMovie.as_view(), name='list_movies'),
    path('administration/edit/movie/<pk>', EditMovie.as_view(), name='edit_movie'),
    path('administration/add/rate/', CreateMovieRate.as_view(), name='create_movie_rate'),
    # path('movies/', Movies.as_view(), name='movies'),
    path('serializer/', SerializerView.as_view(), name='serializer'),
    path('detail/<pk>', SerializerDetail.as_view(), name='detail'),
    path('movie/', MovieListView.as_view(), name='movie_list_create'),
    path('movie/<pk>', MovieUpdateView.as_view(), name='movie_detail_update_delete'),
    path('movies/<int:pk>/', ViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy', 'patch': 'partial_update'}), name='first'),
    path('movies/', ViewSets.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update'}), name='second'),
    path('movies/download', MoviesDownloader.as_view(), name='download'),
    path('movies/suggest', SuggestedMovies.as_view(), name='suggested_movies'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie_project/movie_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie_app.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        path(f'api/{settings.API_VERSION}/', include(('movie_app.api.urls', 'movie_app.api'), namespace='api-movie_app')),

    ] + urlpatterns

movie_project/movie_app/models.py
from django.db import models
from django.contrib.auth import get_user_model
from .choices import GENRES, RATING, ROLES, DEFAULT_GENRE


User = get_user_model()


class MoviePerson(models.Model):
    name = models.CharField(max_length=30)
    age = models.IntegerField()
    role = models.CharField(max_length=25, choices=ROLES)

    def __str__(self):
        return '{} is an {}'.format(self.name, self.role)


class Movie(models.Model):
    title = models.CharField(max_length=50)
    duration = models.IntegerField()
    detail = models.TextField(max_length=150)
    poster = models.ImageField(upload_to='movie_app/posters', max_length=100, default=None)
    movie_people = models.ManyToManyField(MoviePerson)
    trailer_url = models.URLField()
    genre = models.CharField(max_length=50, choices=GENRES, default=DEFAULT_GENRE)
    rating = models.FloatField(null=True, blank=True)
    original_language = models.CharField(max_length=50)
    release_date = models.DateField()
    country = models.CharField(max_length=50)

    def __str__(self):
        return self.title

    def image_url(self):
        if self.poster and hasattr(self.poster, 'url'):
            return self.poster.url


class MovieRate(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=150)
    rating = models.IntegerField(choices=RATING)

    def __str__(self):
        return '{} has {} of rate from {}'.format(self.movie, self.rating, self.user)


class UserToken(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=100)


class MovieSearch(models.Model):
    title = models.CharField(max_length=50)
    duration = models.IntegerField(null=True)
    detail = models.TextField(max_length=150)
    genre = models.CharField(max_length=50)
    original_language = models.CharField(max_length=50)
    release_date = models.DateField()
    country = models.CharField(max_length=50)
    poster = models.ImageField(upload_to='movie_app/posters', null=True, max_length=100, default=None, blank=True)
    actor = models.ManyToManyField('Actor')
    director = models.ForeignKey('Director', on_delete=models.CASCADE, null=True)


class Actor(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Director(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Suggest(models.Model):
    movie_title = models.CharField(max_length=100)

movie_project/templates/movie_app/admin/list/movie.html
{% extends 'adminlte/base.html' %}

{% block content %}
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Movie List</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body no-padding">
                <table class="table table-condensed">
                    <tbody>
                    <tr>
                        <th style="width: 10px">ID</th>
                        <th>Title</th>
                        <th>Duration</th>
                        <th>Detail</th>
                        <th>Poster</th>
                        <th>Characters</th>
                        <th>Trailer</th>
                        <th>Genre</th>
                        <th>Language</th>
                        <th>Release Date</th>
                        <th>Country</th>
                    </tr>
                    <tr>
                        {% if movie_list %}
                            {% for movie in movie_list %}
                                <tr>
                                    <td>{{ movie.id }}</td>
                                    <th class="field-__str__">
                                        <a href="{% url 'movie_app:edit_movie' movie.id %}" class="text">
                                            <div class="text"><span>{{ movie.title }}</span></div>
                                        </a>
                                    </th>
                                    <td class="field-__str__">
                                        <div class="text"><span>{{ movie.duration }}</span></div>
                                    </td>
                                    <td class="field-__str__">
                                        <div class="text"><span>{{ movie.detail }}</span></div>
                                    </td>
                                    {% if movie.poster  %}
                                    <td class="field-__str__">
                                        <img src="{{ movie.poster.url|default_if_none:'#' }}" alt="poster" height="50%"
                                             width="50%">
                                    </td>
                                    {% endif %}
                                    <td class="field-__str__">
                                        {% for actor in movie.movie_people.all %}
                                            <div class="text"><span>{{ actor.name }}</span></div>
                                        {% endfor %}
                                    </td>
                                    <td class="field-__str__">
                                        <div class="text"><span>{{ movie.trailer_url }}</span></div>
                                    </td>
                                    <td class="field-__str__">
                                        <div class="text"><span>{{ movie.genre }}</span></div>
                                    </td>
                                    <td class="field-__str__">
                                        <div class="text"><span>{{ movie.original_language }}</span></div>
                                    </td>
                                    <td class="field-__str__">
                                        <div class="text"><span>{{ movie.release_date }}</span></div>
                                    </td>
                                    <td class="field-__str__">
                                        <div class="text"><span>{{ movie.country }}</span></div>
                                    </td>
                                </tr>

                            {% endfor %}
                        {% else %}
                            <tr>
                                <td><p>Any person have been registered yet</p></td>
                            </tr>
                        {% endif %}

                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
    </div>
{% endblock %}

movie_project/templates/movie_app/admin/list/person.html
{% extends 'adminlte/base.html' %}

{% block content %}
    <div class="col-md-5">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">People List</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body no-padding">
                <table class="table table-condensed">
                    <tbody>
                    <tr>
                        <th></th>
                        <th style="width: 10px">ID</th>
                        <th>Name</th>
                        <th>Age</th>
                        <th>Role</th>
                    </tr>
                    <tr>
                        {% if movieperson_list %}
                            {% for person in movieperson_list %}
                                <tr>
                                    <th scope="col" class="action-checkbox-column">
                                        <div class="text"><span><input type="checkbox" id="action-toggle"></span></div>
                                        <div class="clear"></div>
                                    </th>
                                    <td>{{ person.id }}</td>
                                    <th class="field-__str__">
                                        <a href="{% url 'movie_app:edit_person' person.id %}" class="text">
                                            <div class="text"><span>{{ person.name }}</span></div>
                                        </a>
                                    </th>
                                    <td class="field-__str__">
                                        <div class="text"><span>{{ person.age }}</span></div>
                                    </td>
                                    <td class="field-__str__">
                                        <div class="text"><span>{{ person.role }}</span></div>
                                    </td>

                                </tr>

                            {% endfor %}
                        {% else %}
                            <tr>
                                <td><p>Any person have been registered yet</p></td>
                            </tr>
                        {% endif %}

                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
    </div>
{% endblock %}